FROM mixeme/columbo:python-centos-7

# Install packages required for `PyQt5`
RUN	yum -y install	qt5-qtbase-devel qgnomeplatform qt5-qtstyleplugins \
					libxkbcommon-x11-devel \
	&& yum clean all
# Package `libxkbcommon-x11` solves issue:
# > qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.

# Make symlink for `qmake`
RUN ln -s /usr/bin/qmake-qt5 /usr/bin/qmake

# Install Python packages with `pip`
RUN python3.9 -m pip install --upgrade pip
RUN yum install -y gcc make
RUN yum -y install dbus-devel glib2-devel
RUN python3.9 -m pip install dbus-python dbus-next
RUN yum -y groupinstall "Development Tools"
#RUN python3.9 -m pip install pyqt5-sip==12.7.0
#RUN yum -y install python36-pyqt5-sip
RUN	python3.9 -m pip install --no-binary=:all: pyqt5 --config-settings --confirm-license= --verbose \
	&& python3.9 -m pip install pyinstaller \
	&& python3.9 -m pip cache purge

# Got from https://github.com/jozo/docker-pyqt5/blob/master/default/Dockerfile
# This fix: libGL error: No matching fbConfigs or visuals found
ENV LIBGL_ALWAYS_INDIRECT=1

RUN mkdir /project
WORKDIR /project

# Only after all packages installation!
# Make a symlink to the installed Python 3.9
RUN ln -s /usr/local/bin/python3.9 /usr/local/bin/python3

# Define default command for execution
CMD ["/bin/bash", "/project/scripts/build-lnx.sh", "onedir"]

# Image build
# docker build --tag mixeme/columbo:centos-7 --file scripts/docker/Dockerfile-centos7-x86_64_new scripts/docker
#
# Test run from source
# docker run --user $(id -u):$(id -g) -it --name columbo-build -v $PWD:/project -v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro -v /etc/shadow:/etc/shadow:ro -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix mixeme/columbo:centos-7-$(uname -m) python3 main.py
#
# Build binary
# docker run --user $(id -u):$(id -g) -it --rm -v $PWD:/project -v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro -v /etc/shadow:/etc/shadow:ro -e TAG=centos7 mixeme/columbo:centos-7-$(uname -m)
