FROM centos:7

RUN yum -y install epel-release
RUN yum -y groupinstall "Development Tools"
RUN yum -y install openssl-devel libffi-devel bzip2-devel wget
RUN mkdir /pybuild \
	&& cd /pybuild \
	&& wget https://www.python.org/ftp/python/3.9.18/Python-3.9.18.tgz \
	&& tar xvf Python-*.tgz \
	&& cd Python-3.9*/ \
	&& ./configure --enable-optimizations --prefix=/opt/python --enable-shared LDFLAGS="-Wl,-rpath /usr/local/lib" \
	&& make altinstall \
	&& cd / \
	&& rm -R /pybuild
RUN yum -y install qt5-qtbase qt5-qtbase-devel
RUN python3.9 -m pip install --upgrade pip \
	&& python3.9 -m pip install pyqt5-sip
RUN python3.9 -m pip install pyqt5 --config-settings --confirm-license= --verbose

# && yum -y install qt5-qtstyleplugins
#--config-settings --confirm-license= --verbose
# pyinstaller
# --prefix=/opt/python
# --prefix=/usr/local

#	&& apt install -y git \
#	python3 python3-pip python3-pyqt5 \
#	qt5-gtk2-platformtheme qt5-gtk-platformtheme qt5-style-plugins 
#RUN python3 -m pip install pyinstaller

# Got from https://github.com/jozo/docker-pyqt5/blob/master/default/Dockerfile
# This fix: libGL error: No matching fbConfigs or visuals found
#ENV LIBGL_ALWAYS_INDIRECT=1

#RUN mkdir /project
#WORKDIR /project

#CMD ["/bin/bash", "/project/scripts/build-lnx.sh", "onedir"]

# Image build
# docker build --tag mixeme/columbo-build:centos-7 --file Docker-centos7 scripts/docker
#
# Test run from source
# docker run --user $(id -u):$(id -g) -it --rm --name columbo-build -v $PWD:/project -v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro -v /etc/shadow:/etc/shadow:ro -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix mixeme/columbo-build:debian-bullseye python3 main.py
#
# Build binary
# docker run --user $(id -u):$(id -g) -it --rm --name columbo-build -v $PWD:/project -v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro -v /etc/shadow:/etc/shadow:ro mixeme/columbo-build:debian-bullseye
