FROM python:3.9-buster

# Suppress prompting from apt
ARG DEBIAN_FRONTEND=noninteractive

# Install basic packages
RUN apt update -y && apt install -y apt-utils wget

# Packages required for `dbus-python` compilation: libdbus-1-dev libdbus-glib-1-dev
# Packages required for `PyQt5` compilation:
RUN apt install -y libdbus-1-dev libdbus-glib-1-dev
RUN apt install -y qt5-default qt5-style-plugins \
	qt5-gtk-platformtheme qt5-flatpak-platformtheme \
	&& apt clean

# Install Python packages with `pip`
RUN python3.9 -m pip install --no-binary=:all: pyqt5 --config-settings --confirm-license= --verbose
RUN python3.9 -m pip install --upgrade pip \
	&& python3.9 -m pip install pyinstaller dbus-python dbus-next
	&& python3.9 -m pip cache purge

# Got from https://github.com/jozo/docker-pyqt5/blob/master/default/Dockerfile
# This fix: libGL error: No matching fbConfigs or visuals found
ENV LIBGL_ALWAYS_INDIRECT=1

# Setup work directory
RUN mkdir /project
WORKDIR /project

# Only after all packages installation!
# Overwrite a symlink to the installed Python 3.9
#RUN rm /usr/bin/python3 && ln -s /usr/local/bin/python3.9 /usr/local/bin/python3

# Define default command for execution
CMD ["/bin/bash", "/project/scripts/build-lnx.sh", "onedir"]

# Image build
# docker build --tag mixeme/columbo:python-buster --file scripts/docker/Dockerfile-deb10-python scripts/docker
#
# Test run from source
# docker run --user $(id -u):$(id -g) -it --rm --name columbo-build -v $PWD:/project -v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro -v /etc/shadow:/etc/shadow:ro -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix mixeme/columbo:python-buster python3 main.py
#
# Build binary
# docker run --user $(id -u):$(id -g) -it --rm -v $PWD:/project -v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro -v /etc/shadow:/etc/shadow:ro -e TAG=deb10 mixeme/columbo:python-buster
