FROM debian:buster

RUN apt update -y \
	&& apt install -y wget git \
	software-properties-common build-essential \
	libffi-dev zlib1g-dev \
	qt5-default qt5-gtk-platformtheme qt5-style-plugins \
	python3-pip python3-pyqt5

# Compile & install CPython 3.9.18 from source
RUN mkdir /pybuild \
	&& cd /pybuild \
	&& wget https://www.python.org/ftp/python/3.9.18/Python-3.9.18.tgz \
	&& tar xvf Python-*.tgz \
	&& cd Python-3.9*/ \
	&& ./configure --enable-optimizations \
	&& make altinstall \
	&& cd / \
	&& rm -R /pybuild
# Overwrite symlink to the installed Python
RUN rm /usr/bin/python3 && ln -s /usr/local/bin/python3.9 /usr/bin/python3

#RUN python3 -m pip install pyinstaller

# Got from https://github.com/jozo/docker-pyqt5/blob/master/default/Dockerfile
# This fix: libGL error: No matching fbConfigs or visuals found
ENV LIBGL_ALWAYS_INDIRECT=1

RUN mkdir /project
WORKDIR /project

#RUN python3 -m pip install pyqt5 pyinstaller


RUN apt install -y libnss3-dev libssl-dev libgdbm-dev libncurses5-dev

# Install Python packages with `pip`
RUN python3.9 -m pip install --upgrade pip \
	&& python3.9 -m pip install pyqt5-sip \
	&& python3.9 -m pip install pyqt5 --config-settings --confirm-license= --verbose

#CMD ["/bin/bash", "/project/scripts/build-lnx.sh", "onedir"]

# Image build
# docker build --tag mixeme/columbo:debian-buster --file scripts/docker/Dockerfile-deb10 scripts/docker
#
# Test run from source
# docker run --user $(id -u):$(id -g) -it --rm --name columbo-build -v $PWD:/project -v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro -v /etc/shadow:/etc/shadow:ro -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix mixeme/columbo:debian-buster python3.9 main.py
#
# Build binary
# docker run --user $(id -u):$(id -g) -it --rm --name columbo-build -v $PWD:/project -v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro -v /etc/shadow:/etc/shadow:ro mixeme/columbo:debian-buster
