FROM centos:7

# The next layer does the following:
#   1. Install group "Development Tools";
#   2. Install packages for CPython compilation (with all modules);
#   3. Download, compile & install CPython 3.9.18 from source;
#   4. Remove installed packages for the compilation by `rollback` command.

RUN yum -y groupinstall "Development Tools" \
	&& yum -y install	gdbm-devel libffi-devel lcov \
						zlib-devel xz-devel bzip2-devel lzma lzma-sdk-devel \
						openssl-devel sqlite-devel expat-devel \
						ncurses-devel readline-devel tk-devel uuid-devel \
	&& yum -y install wget \
	&& mkdir /pybuild \
	&& cd /pybuild \
	&& wget https://www.python.org/ftp/python/3.9.18/Python-3.9.18.tgz \
	&& tar -xzf Python-*.tgz \
	&& cd Python-3.9*/ \
	&& ./configure --enable-optimizations --with-lto --enable-shared LDFLAGS="-Wl,--rpath=/usr/local/lib" \
	&& make altinstall \
	&& cd / \
	&& rm -R /pybuild \
	&& yum -y groupremove "Development Tools" \
	&& yum -y remove	gdbm-devel libffi-devel lcov \
						zlib-devel xz-devel bzip2-devel lzma lzma-sdk-devel \
						openssl-devel sqlite-devel expat-devel \
						ncurses-devel readline-devel tk-devel uuid-devel \
	&& yum -y autoremove \
	&& yum clean all
LABEL python.version=3.9.18

# Image build
# docker build --tag mixeme/columbo:python-centos-7 --file scripts/docker/Dockerfile-python-centos7 scripts/docker
