FROM debian:buster

RUN apt update -y \
	&& apt install -y wget git apt-utils \
	software-properties-common build-essential \
	libffi-dev glib2.0 \
	zlib1g-dev libbz2-dev \
	libssl-dev libnss3-dev \
	libreadline-dev \
	qt5-default qt5-gtk-platformtheme qt5-style-plugins
RUN apt install -y libdbus-1-dev libdbusextended-qt5-dev libdbus-c++-dev libdbus-glib-1-dev

# Compile & install CPython 3.9.18 from source
RUN mkdir /pybuild \
	&& cd /pybuild \
	&& wget https://www.python.org/ftp/python/3.9.18/Python-3.9.18.tgz \
	&& tar -xzf Python-*.tgz \
	&& cd Python-3.9*/ \
	&& ./configure --enable-optimizations --with-lto --enable-shared LDFLAGS="-Wl,--rpath=/usr/local/lib" \
	&& make altinstall \
	&& cd / \
	&& rm -R /pybuild

# Install Python packages with `pip`
RUN python3.9 -m pip install --upgrade pip \
	&& python3.9 -m pip install pyinstaller dbus-python
#RUN	python3.9 -m pip install pyqt5 --config-settings --confirm-license= --verbose
#	&& python3.9 -m pip install pyqt5 --config-settings --confirm-license= --verbose

# Overwrite symlink to the installed Python
#RUN rm /usr/bin/python3 && ln -s /usr/local/bin/python3.9 /usr/bin/python3

# Got from https://github.com/jozo/docker-pyqt5/blob/master/default/Dockerfile
# This fix: libGL error: No matching fbConfigs or visuals found
#ENV LIBGL_ALWAYS_INDIRECT=1

#RUN mkdir /project
#WORKDIR /project

#CMD ["/bin/bash", "/project/scripts/build-lnx.sh", "onedir"]

# Image build
# docker build --tag mixeme/columbo:debian-buster --file scripts/docker/Dockerfile-deb10 scripts/docker
#
# Test run from source
# docker run --user $(id -u):$(id -g) -it --rm --name columbo-build -v $PWD:/project -v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro -v /etc/shadow:/etc/shadow:ro -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY mixeme/columbo:debian-buster python3.9 main.py
#
# Build binary
# docker run --user $(id -u):$(id -g) -it --rm --name columbo-build -v $PWD:/project -v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro -v /etc/shadow:/etc/shadow:ro mixeme/columbo:debian-buster
